### ISSUE TITLE
still maintained? 

### ISSUE THREAD

**Issue by gabrielcsapo** [kenichi/tracklet#7]
I am working on something similar and it seems like you have gotten pretty far. (https://github.com/gabrielcsapo/quantified_self) If you are interested in working on something together let me know. gabecsapo@gmail.com.

If not I totally understand.

**Comment by aaronpk** [comment]
Hey @gabrielcsapo, I've been using my own version of a GPS tracker https://github.com/aaronpk/GPS-Logger-iOS I've  been using it for a couple years now and would be happy to chat about it and see if it's something you're interested in using or contributing to.

**Comment by gabrielcsapo** [comment]
@aaronpk interesting, I was looking to talk to someone about an open source version of https://gyrosco.pe/app/. It is basically a location data aggregator, it would be interesting to work on a more secure platform then relying on 3rd part api's.
